name: thesis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - snakemake-minimal=5.12
  - pandas=1.0.3
  - matplotlib-base
  - hvplot
  - scipy
  - seaborn
  - ficus
