name: thesis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - snakemake-minimal=5.12
  - pandas=1.0.3
  - tabulate
  - matplotlib-base
  - hvplot
  - scipy
  - seaborn
  - ficus
  - sourmash
  - jupyterlab
  - nb_conda_kernels
