name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install xelatex
      run: sudo apt install -y texlive-xetex
    - name: Update conda
      run: conda update -q conda
    - name: Install conda dependencies
      run: conda env create --force --file environment.yml
    - name: Install aggiedown in R environment
      run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate thesis
          snakemake --use-conda install_deps
    - name: Run pipeline
      run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate thesis
          snakemake --use-conda
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_PATH: thesis/_book/thesis.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
